import { TEXT_MEAL_JSON_SCHEMA, validateTextMealProviderOutput, type TextMealEstimationResult } from "@/modules/meals/text-meal-ai";
const OPENAI_RESPONSES_ENDPOINT = "https://api.openai.com/v1/responses";
export const TEXT_MEAL_AI_MODEL_DEFAULT = "gpt-5.6-terra";
export const TEXT_MEAL_AI_TIMEOUT_MS = 20_000;
export const TEXT_MEAL_SYSTEM_PROMPT = `Analiza descripciones de comidas en español y devuelve una estimación nutricional, no un registro de comida. Identifica únicamente los ingredientes mencionados, sus cantidades, unidades y preparación. Para cada ingrediente devuelve normalized_name (nombre alimentario simple), display_name (texto claro para la persona), name (igual a display_name por compatibilidad) y confianza individual. No inventes ingredientes, aceite, salsas ni aderezos que no se hayan indicado.

Las cantidades aproximadas son válidas: estima prudentemente "un tomate pequeño", "una manzana mediana", "un huevo L", lonchas, cucharadas, cucharaditas, latas, tazas y un plato normal. Declara cada equivalencia de peso o cantidad aproximada en assumptions y usa confianza medium o low; no la presentes como exacta.

La preparación explícita tiene prioridad. Si se indica cocido, cocinada, a la plancha, frito, asado, horneado, hervido o equivalente, usa ese estado. Si no se indica preparación, aplica crudo por defecto a pollo, pavo, carnes, pescados, arroz, pasta, legumbres secas, verduras y huevos: "200 g de pollo debe tratarse como pollo crudo" y "100 g de arroz debe tratarse como arroz crudo". Incluye la preparación asumida tanto en el ingrediente como en assumptions. No apliques ese valor por defecto a productos listos para consumir como jamón, queso, pan, leche, yogur, salsas o conservas.

Usa needs-clarification solo cuando no puedas identificar el alimento, haya interpretaciones totalmente distintas, no exista una referencia razonable de cantidad o sea imposible una aproximación prudente. No solicites aclaración solo porque una cantidad sea aproximada. Usa solo estas unidades: g, ml, unidad, loncha, cucharadita, cucharada, taza, lata o plato (en singular o plural). Calcula macros finitos y no negativos. No des consejos médicos, no afirmes exactitud ni que la comida se ha guardado. Devuelve únicamente JSON conforme al JSON Schema.`;
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null; }
function extract(body: unknown): string | null { if (!record(body) || body.status !== "completed") return null; if (typeof body.output_text === "string" && body.output_text.trim()) return body.output_text; if (!Array.isArray(body.output)) return null; for (const item of body.output) if (record(item) && Array.isArray(item.content)) for (const content of item.content) if (record(content) && content.type === "output_text" && typeof content.text === "string") return content.text; return null; }
export async function estimateTextMealWithOpenAi(description: string, options: { apiKey: string; model?: string; fetchImpl?: typeof fetch }): Promise<TextMealEstimationResult> { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), TEXT_MEAL_AI_TIMEOUT_MS); try { const response = await (options.fetchImpl ?? fetch)(OPENAI_RESPONSES_ENDPOINT, { method: "POST", headers: { Authorization: `Bearer ${options.apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: options.model ?? TEXT_MEAL_AI_MODEL_DEFAULT, input: [{ role: "system", content: TEXT_MEAL_SYSTEM_PROMPT }, { role: "user", content: description }], text: { format: { type: "json_schema", name: "text_meal_estimation", strict: true, schema: TEXT_MEAL_JSON_SCHEMA } }, store: false, reasoning: { effort: "low" }, max_output_tokens: 2500 }), signal: controller.signal }); if (response.status === 408) return { status: "error", code: "provider-timeout" }; if (!response.ok) return { status: "error", code: "provider-error" }; const text = extract(await response.json()); if (!text) return { status: "error", code: "invalid-ai-response" }; try { return validateTextMealProviderOutput(JSON.parse(text)); } catch { return { status: "error", code: "invalid-ai-response" }; } } catch (error) { return record(error) && error.name === "AbortError" ? { status: "error", code: "provider-timeout" } : { status: "error", code: "provider-error" }; } finally { clearTimeout(timeout); } }
