"use client";

import { INVENTORY_CATEGORIES, INVENTORY_CATEGORY_LABELS } from "@/modules/inventory/inventory-categories";
import { getVoiceInventoryDraftReadiness, getVoiceInventoryDraftStatus, normalizeEditedVoiceInventoryDraftItem, type VoiceInventoryDraftItem } from "@/modules/inventory/voice-inventory-batch";

const issueLabels: Record<string, string> = { "quantity-missing": "Cantidad pendiente", "unit-missing": "Unidad pendiente", "location-unconfirmed": "Ubicación sin confirmar", "package-size-missing": "Falta el tamaño del paquete", "nutrition-incomplete": "Nutrición incompleta", "nutrition-basis-mismatch": "La base nutricional no coincide con la unidad", "low-confidence": "Confianza baja", "ambiguous-product": "Corrige el nombre ambiguo" };
const foodStateLabels: Record<VoiceInventoryDraftItem["food_state"], string> = { raw: "Crudo", cooked: "Cocinado", processed: "Procesado", not_applicable: "No aplicable", unknown: "Sin determinar" };

export function VoiceInventoryBatchPreview({ items, onChange, submissionId, saving, onSave }: { items: VoiceInventoryDraftItem[]; onChange: (items: VoiceInventoryDraftItem[]) => void; submissionId: string | null; saving: boolean; onSave: () => void }) {
  function update(id: string, field: keyof VoiceInventoryDraftItem, value: unknown) { onChange(items.map((item) => item.client_id === id ? normalizeEditedVoiceInventoryDraftItem(item, field, value) : item)); }
  const canSave = Boolean(submissionId) && items.length > 0 && items.every((item) => getVoiceInventoryDraftReadiness(item).saveReady) && !saving;
  return <section aria-live="polite" className="inventory-products" aria-labelledby="voice-inventory-preview-title">
    <div className="inventory-section__heading"><div><span className="inventory-section__kicker">Borrador</span><h3 id="voice-inventory-preview-title">Revisar productos detectados</h3></div><span className="inventory-count">{items.length}</span></div>
    <div className="inventory-groups">{items.map((item) => { const readiness = getVoiceInventoryDraftReadiness(item); return <article className="inventory-group" key={item.client_id}><div className="inventory-group__heading"><strong>{getVoiceInventoryDraftStatus(item)}</strong><button className="inventory-delete-button" type="button" disabled={saving} onClick={() => onChange(items.filter((draft) => draft.client_id !== item.client_id))}>Eliminar</button></div>
      <div className="meal-log-form"><label className="field"><span>Nombre</span><input disabled={saving} value={item.name} maxLength={120} onChange={(e) => update(item.client_id, "name", e.target.value)} /></label><label className="field"><span>Cantidad</span><input disabled={saving} type="number" min="0" step="any" value={item.quantity ?? ""} onChange={(e) => update(item.client_id, "quantity", e.target.value === "" ? null : Number(e.target.value))} /></label><label className="field"><span>Unidad</span><select disabled={saving} value={item.unit ?? ""} onChange={(e) => update(item.client_id, "unit", e.target.value || null)}><option value="">Pendiente</option>{["ud", "g", "kg", "ml", "l"].map((v) => <option key={v}>{v}</option>)}</select></label><label className="field"><span>Ubicación</span><select disabled={saving} value={item.location ?? ""} onChange={(e) => update(item.client_id, "location", e.target.value || null)}><option value="">Pendiente</option><option value="pantry">Despensa</option><option value="fridge">Nevera</option><option value="freezer">Congelador</option></select></label><label className="field"><span>Categoría</span><select disabled={saving} value={item.category ?? ""} onChange={(e) => update(item.client_id, "category", e.target.value || null)}><option value="">Sin categoría</option>{INVENTORY_CATEGORIES.map((v) => <option key={v} value={v}>{INVENTORY_CATEGORY_LABELS[v]}</option>)}</select></label><label className="field"><span>Base nutricional</span><select disabled={saving} value={item.nutrition_basis ?? ""} onChange={(e) => update(item.client_id, "nutrition_basis", e.target.value || null)}><option value="">Pendiente</option><option value="per_100g">Por 100 g</option><option value="per_100ml">Por 100 ml</option><option value="per_unit">Por unidad</option></select></label>{([ ["calories", "Calorías"], ["protein_g", "Proteína (g)"], ["carbs_g", "Carbohidratos (g)"], ["fat_g", "Grasa (g)"] ] as const).map(([field, label]) => <label className="field" key={field}><span>{label}</span><input disabled={saving} type="number" min="0" step="any" value={item[field] ?? ""} onChange={(e) => update(item.client_id, field, e.target.value === "" ? null : Number(e.target.value))} /></label>)}</div>
      {item.issues.length ? <ul>{item.issues.map((issue) => <li key={issue}>{issueLabels[issue]}</li>)}</ul> : <p>Sin avisos pendientes.</p>}
      <p className="muted">Estado: {foodStateLabels[item.food_state]}. Estimación IA ({item.confidence === "high" ? "confianza alta" : item.confidence === "medium" ? "confianza media" : "confianza baja"}): {item.nutrition_assumptions}</p>
      {readiness.requiresReview && readiness.structuralReady ? <label><input type="checkbox" disabled={saving} checked={Boolean(item.review_acknowledged)} onChange={(e) => update(item.client_id, "review_acknowledged", e.target.checked)} /> He revisado este producto</label> : null}
    </article>; })}</div>
    <button className="inventory-button" type="button" disabled={!canSave} onClick={onSave}>{saving ? "Añadiendo productos…" : `Añadir ${items.length} productos al inventario`}</button>
  </section>;
}
