import { deleteSavedDailyPlanAction } from "@/app/plan/actions";
import { CookSavedPlanMealButton } from "@/components/plan/CookSavedPlanMealButton";
import { MEAL_TYPE_LABELS } from "@/modules/meals/meal-types";
import { formatPlanDateLabel, getPlanDateOptions } from "@/modules/plans/plan-date";
import type { SavedDailyPlan } from "@/modules/plans/saved-daily-plans";

const number = (value: number) => new Intl.NumberFormat("es-ES", { maximumFractionDigits: 1 }).format(value);
function PlanCard({ plan, todayKey }: { plan: SavedDailyPlan; todayKey: string }) { const complete = Object.values(plan.completed_meals).filter(Boolean).length; return <article className="saved-plan"><div className="saved-plan__header"><div><h3>Plan para {formatPlanDateLabel(plan.plan_date, todayKey)}</h3><p>{number(plan.total.calories)} kcal · P {number(plan.total.protein_g)} g · C {number(plan.total.carbs_g)} g · G {number(plan.total.fat_g)} g</p><p><strong>{complete} de 4</strong> comidas registradas</p></div><form action={deleteSavedDailyPlanAction}><input type="hidden" name="plan_id" value={plan.id} /><button type="submit">Eliminar plan</button></form></div><details><summary>Ver las cuatro comidas</summary>{plan.meals.map((meal) => <section className="saved-plan-meal" key={meal.meal_type}><strong>{MEAL_TYPE_LABELS[meal.meal_type]}: {meal.title}</strong><p>{meal.description}</p><CookSavedPlanMealButton planId={plan.id} mealType={meal.meal_type} completed={Boolean(plan.completed_meals[meal.meal_type])} /></section>)}</details></article>; }
export function SavedDailyPlans({ plans, todayKey }: { plans: SavedDailyPlan[]; todayKey: string }) { const dates = getPlanDateOptions(todayKey); const byDate = new Map(plans.map((plan) => [plan.plan_date, plan])); const others = plans.filter((plan) => !dates.includes(plan.plan_date)).sort((a,b) => b.plan_date.localeCompare(a.plan_date) || b.created_at.localeCompare(a.created_at)); return <section className="saved-plans" aria-labelledby="saved-plans-title"><div className="saved-plans__heading"><span className="plan-eyebrow">Tu colección</span><h2 id="saved-plans-title">Tus planes guardados</h2><p>Solo al cocinar se comprueba y descuenta el inventario.</p></div><h3>Próximos siete días</h3><div className="weekly-plan-agenda">{dates.map((date) => { const plan = byDate.get(date); return <div className={`weekly-plan-slot ${plan ? "weekly-plan-slot--saved" : "weekly-plan-slot--empty"}`} key={date}><h4>{formatPlanDateLabel(date, todayKey)}</h4>{plan ? <><p><strong>Plan guardado</strong></p><p>{number(plan.total.calories)} kcal · P {number(plan.total.protein_g)} g · C {number(plan.total.carbs_g)} g · G {number(plan.total.fat_g)} g</p><p>{Object.values(plan.completed_meals).filter(Boolean).length} de 4 comidas registradas</p><details><summary>Acceso a los detalles</summary><PlanCard plan={plan} todayKey={todayKey} /></details></> : <p><strong>Sin plan</strong></p>}</div>; })}</div>{others.length ? <><h3>Otros planes guardados</h3>{others.map((plan) => <PlanCard key={plan.id} plan={plan} todayKey={todayKey} />)}</> : null}</section>; }
