"use client";
import { useMemo, useRef, useState } from "react";
import { consumeAiMealInventoryAction } from "@/app/macros/actions";
import { PendingSubmitButton } from "@/components/forms/PendingSubmitButton";
import { calculateAiInventoryTotals, convertEstimatedQuantity, suggestInventoryMatch, validateAiInventoryLine } from "@/modules/meals/ai-inventory-reconciliation";
import type { MealBuilderInventoryItem, MealBuilderLine } from "@/modules/meals/meal-builder";
import { MEAL_TYPES, MEAL_TYPE_LABELS } from "@/modules/meals/meal-types";
import type { TextMealEstimationResult } from "@/modules/meals/text-meal-ai";

type Props={result: Extract<TextMealEstimationResult,{status:"success"}>;mealMode:"text-ai"|"photo-ai";items:MealBuilderInventoryItem[];inventoryUnavailable:boolean};
export function AiMealInventoryReconciliation({result,mealMode,items,inventoryUnavailable}:Props){
 const submissionId=useRef(crypto.randomUUID()).current;
 const matches=useMemo(()=>result.ingredients.map((ingredient)=>suggestInventoryMatch(ingredient.normalized_name,items)),[result.ingredients,items]);
 const [selected,setSelected]=useState<(string|null)[]>(()=>matches.map((match)=>match.suggestedItemId));
 const [quantities,setQuantities]=useState<(string)[]>(()=>result.ingredients.map((ingredient,index)=>{const item=items.find((candidate)=>candidate.id===matches[index].suggestedItemId);const converted=item?convertEstimatedQuantity(ingredient.quantity,ingredient.unit,item.unit):null;return converted===null?"":String(converted)}));
 const lines=useMemo(()=>selected.map((id,index)=>{const item=items.find((candidate)=>candidate.id===id);return item?{...item,consumed_quantity:Number(quantities[index])}:null;}).filter(Boolean) as MealBuilderLine[],[items,quantities,selected]);
 const errors=result.ingredients.map((_,index)=>validateAiInventoryLine(items.find((item)=>item.id===selected[index]),Number(quantities[index])));
 const duplicate=selected.some((id,index)=>id!==null&&selected.indexOf(id)!==index); const ready=!inventoryUnavailable&&!duplicate&&errors.every((error)=>!error)&&lines.length===result.ingredients.length;
 const totals=ready?calculateAiInventoryTotals(lines):null;
 return <section className="ai-inventory-reconciliation"><h4>Relacionar con tu inventario</h4>{inventoryUnavailable?<p className="auth-message error">No se pudo cargar tu inventario. Puedes registrar solo los macros estimados.</p>:null}<p className="muted">Al registrar con inventario, LaKitchen utilizará los valores nutricionales y cantidades reales de tus productos.</p>
 <form action={consumeAiMealInventoryAction} className="meal-log-form macros-meal-form"><input type="hidden" name="meal_mode" value={mealMode}/><input type="hidden" name="submission_id" value={submissionId}/><input type="hidden" name="lines" value={ready?JSON.stringify(lines.map(({id,consumed_quantity})=>({item_id:id,consumed_quantity}))):"[]"}/><label className="field"><span>Nombre</span><input name="meal_name" required defaultValue={result.suggested_name}/></label><label className="field"><span>Tipo de comida</span><select name="meal_type" required defaultValue=""><option value="" disabled>Selecciona un tipo</option>{MEAL_TYPES.map(type=><option key={type} value={type}>{MEAL_TYPE_LABELS[type]}</option>)}</select></label>
 {result.ingredients.map((ingredient,index)=>{const item=items.find(candidate=>candidate.id===selected[index]);const error=errors[index];return <div className="text-ai-ingredients" key={`${ingredient.name}-${index}`}><strong>{ingredient.display_name}</strong><span>Estimado: {ingredient.quantity} {ingredient.unit}{ingredient.preparation?` · ${ingredient.preparation}`:""}</span><label className="field"><span>Producto real</span><select value={selected[index]??""} onChange={event=>{const id=event.target.value||null;const next=items.find(item=>item.id===id);setSelected(values=>values.map((value,i)=>i===index?id:value));setQuantities(values=>values.map((value,i)=>i===index?(next&&convertEstimatedQuantity(ingredient.quantity,ingredient.unit,next.unit) !== null?String(convertEstimatedQuantity(ingredient.quantity,ingredient.unit,next.unit)):""):value));}}><option value="">Selecciona un producto</option>{items.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></label>{item?<><span>Stock: {item.quantity} {item.unit}</span><label className="field"><span>Cantidad a descontar ({item.unit})</span><input type="number" min="0" step="0.01" value={quantities[index]} onChange={event=>setQuantities(values=>values.map((value,i)=>i===index?event.target.value:value))}/></label>{!error?<span>Relación lista para revisar.</span>:<span className="auth-message error">{error} {!item || undefined}</span>}{!item || !error?null:<a href="/inventory">Completar macros en Inventario</a>}</>:<span className="auth-message error">{matches[index].ambiguous?"Hay varias coincidencias posibles; elige una.":"Sin producto relacionado."}</span>}</div>})}
 {duplicate?<p className="auth-message error">No puedes descontar el mismo producto dos veces; combina la cantidad en una sola relación.</p>:null}<div className="text-ai-totals"><strong>Total según tu inventario</strong><span>{totals?`${totals.calories} kcal · P ${totals.protein_g} g · C ${totals.carbs_g} g · G ${totals.fat_g} g`:"Completa todas las relaciones válidas para calcularlo."}</span></div><PendingSubmitButton className="button macros-submit" disabled={!ready} idleLabel="Registrar y descontar inventario" pendingLabel="Registrando y descontando…" /></form></section>
}
