import { describe, expect, it } from "vitest";
import { PHOTO_MEAL_AI_MODEL_DEFAULT, estimatePhotoMealWithOpenAi } from "@/lib/openai/photo-meal-estimation";
const ingredient = { name: "Arroz", quantity: 150, unit: "g", preparation: "cocido", calories: 195, protein_g: 4, carbs_g: 42, fat_g: .5 };
const success = { status: "success", suggested_name: "Arroz", ingredients: [ingredient], assumptions: [], confidence: "medium", message: null };
const clarification = { status: "needs-clarification", suggested_name: null, ingredients: null, assumptions: null, confidence: null, message: "No puedo estimar cuánto arroz se consumió aproximadamente." };
const response = (status: number, body: unknown) => ({ ok: status >= 200 && status < 300, status, json: async () => body }) as Response;
const completed = (value: unknown) => response(200, { status: "completed", output_text: JSON.stringify(value) });
describe("photo meal OpenAI provider", () => {
  it("sends the complete strict multimodal request", async () => { let body: any; await estimatePhotoMealWithOpenAi("data:image/jpeg;base64,/9j/", "con aceite", { apiKey: "key", fetchImpl: async (_url, init) => { body = JSON.parse(String(init?.body)); return completed(success); } }); expect(body.model).toBe(PHOTO_MEAL_AI_MODEL_DEFAULT); expect(body.input[1].content).toEqual(expect.arrayContaining([expect.objectContaining({ type: "input_text", text: "con aceite" }), expect.objectContaining({ type: "input_image", image_url: "data:image/jpeg;base64,/9j/", detail: "high" })])); expect(body.text.format.strict).toBe(true); expect(body.store).toBe(false); expect(body.reasoning).toEqual({ effort: "low" }); expect(body.max_output_tokens).toBe(2500); });
  it("uses fallback context and normalizes success and clarification", async () => { expect(await estimatePhotoMealWithOpenAi("data:image/jpeg;base64,/9j/", "", { apiKey: "key", fetchImpl: async (_u, i) => { expect(String(i?.body)).toContain("Analiza esta fotografía de comida."); return completed(success); } })).toMatchObject({ status: "success", total: { calories: 195 } }); expect(await estimatePhotoMealWithOpenAi("data:image/jpeg;base64,/9j/", "", { apiKey: "key", fetchImpl: async () => completed(clarification) })).toEqual({ status: "needs-clarification", message: clarification.message }); });
  it("maps provider, incomplete, refusal, and invalid responses safely", async () => { const invalids = [response(408, {}), response(500, {}), response(200, { status: "incomplete" }), response(200, { status: "completed", output: [{ content: [{ type: "refusal" }] }] }), response(200, { status: "completed" }), response(200, { status: "completed", output_text: "not json" }), completed({ ...success, message: "bad" }), completed({ ...clarification, ingredients: [ingredient] })]; for (const item of invalids) { const result = await estimatePhotoMealWithOpenAi("data:image/jpeg;base64,/9j/", "", { apiKey: "key", fetchImpl: async () => item }); expect(result.status).toBe("error"); } });
});
