import { describe, expect, it } from "vitest";
import { calculateTextMealTotals, textMealRequestSchema, validateTextMealProviderOutput } from "@/modules/meals/text-meal-ai";

const ingredient = { name: "Pechuga de pollo", quantity: 240, unit: "g", preparation: "a la plancha", calories: 396, protein_g: 74.4, carbs_g: 0, fat_g: 8.6 };
const success = () => ({ status: "success", suggested_name: "Pollo con arroz", ingredients: [ingredient], assumptions: ["Se asumió cocinado sin salsa"], confidence: "high", message: null });
const clarification = () => ({ status: "needs-clarification", suggested_name: null, ingredients: null, assumptions: null, confidence: null, message: "No puedo estimar cuánto arroz se consumió aproximadamente." });

describe("text meal AI validation", () => {
  it("validates input boundaries", () => { expect(textMealRequestSchema.safeParse({ description: "pollo" }).success).toBe(true); expect(textMealRequestSchema.safeParse({ description: "" }).success).toBe(false); expect(textMealRequestSchema.safeParse({ description: "ab" }).success).toBe(false); expect(textMealRequestSchema.safeParse({ description: "a".repeat(2001) }).success).toBe(false); });
  it("accepts and normalizes the complete Structured Output success shape", () => { expect(validateTextMealProviderOutput(success())).toEqual({ status: "success", suggested_name: "Pollo con arroz", ingredients: [ingredient], total: { calories: 396, protein_g: 74.4, carbs_g: 0, fat_g: 8.6 }, assumptions: ["Se asumió cocinado sin salsa"], confidence: "high" }); });
  it("accepts and normalizes the complete Structured Output clarification shape", () => { expect(validateTextMealProviderOutput(clarification())).toEqual({ status: "needs-clarification", message: clarification().message }); });
  it("rejects incompatible status field combinations and additional properties", () => { const invalid = [{ ...success(), message: "No nulo" }, { ...success(), ingredients: null }, { ...success(), confidence: null }, { ...success(), suggested_name: null }, { ...clarification(), message: null }, { ...clarification(), ingredients: [ingredient] }, { ...clarification(), suggested_name: "Nombre" }, { ...clarification(), assumptions: ["Suposición"] }, { ...clarification(), confidence: "low" }, { ...success(), extra: true }]; for (const value of invalid) expect(validateTextMealProviderOutput(value)).toEqual({ status: "error", code: "invalid-ai-response" }); });
  it("rejects invalid ingredients and oversized totals", () => { for (const change of [{ quantity: 0 }, { quantity: -1 }, { calories: -1 }, { name: "" }, { unit: "" }, { quantity: Infinity }]) expect(validateTextMealProviderOutput({ ...success(), ingredients: [{ ...ingredient, ...change }] })).toEqual({ status: "error", code: "invalid-ai-response" }); expect(validateTextMealProviderOutput({ ...success(), ingredients: Array.from({ length: 21 }, () => ingredient) })).toEqual({ status: "error", code: "invalid-ai-response" }); expect(calculateTextMealTotals([{ ...ingredient, calories: 0.04, protein_g: 0.04, carbs_g: 0.04, fat_g: 0.04 }, { ...ingredient, calories: 0.05, protein_g: 0.05, carbs_g: 0.05, fat_g: 0.05 }])).toEqual({ calories: 0.1, protein_g: 0.1, carbs_g: 0.1, fat_g: 0.1 }); expect(calculateTextMealTotals([{ ...ingredient, calories: 5001 }, { ...ingredient, calories: 5001 }])).toBeNull(); });
});
