import { describe, expect, it } from "vitest";
import { estimateTextMealWithOpenAi } from "@/lib/openai/text-meal-estimation";

const success = { status: "success", suggested_name: "Comida", ingredients: [{ name: "Arroz", quantity: 150, unit: "g", preparation: "cocido", calories: 195, protein_g: 4, carbs_g: 42, fat_g: 0.5 }], assumptions: [], confidence: "medium", message: null };
const clarification = { status: "needs-clarification", suggested_name: null, ingredients: null, assumptions: null, confidence: null, message: "No puedo estimar cuánto arroz se consumió aproximadamente." };
const response = (status: number, body: unknown) => ({ ok: status >= 200 && status < 300, status, json: async () => body }) as Response;
const completed = (output: unknown) => response(200, { status: "completed", output_text: JSON.stringify(output) });

describe("text meal OpenAI provider", () => {
  it("normalizes the complete Structured Output success shape", async () => { let body = ""; const result = await estimateTextMealWithOpenAi("150 g arroz", { apiKey: "key", fetchImpl: async (_url, init) => { body = String(init?.body); return completed(success); } }); expect(result).toEqual({ status: "success", suggested_name: "Comida", ingredients: success.ingredients, total: { calories: 195, protein_g: 4, carbs_g: 42, fat_g: 0.5 }, assumptions: [], confidence: "medium" }); expect(body).toContain('"store":false'); expect(body).toContain('"effort":"low"'); });
  it("normalizes the complete Structured Output clarification shape", async () => { expect(await estimateTextMealWithOpenAi("arroz", { apiKey: "key", fetchImpl: async () => completed(clarification) })).toEqual({ status: "needs-clarification", message: clarification.message }); });
  it("rejects incompatible complete provider payloads", async () => { expect(await estimateTextMealWithOpenAi("arroz", { apiKey: "key", fetchImpl: async () => completed({ ...success, message: "No nulo" }) })).toEqual({ status: "error", code: "invalid-ai-response" }); expect(await estimateTextMealWithOpenAi("arroz", { apiKey: "key", fetchImpl: async () => completed({ ...clarification, ingredients: success.ingredients }) })).toEqual({ status: "error", code: "invalid-ai-response" }); });
  it("handles provider failures and malformed responses", async () => { expect(await estimateTextMealWithOpenAi("arroz", { apiKey: "key", fetchImpl: async () => response(500, {}) })).toEqual({ status: "error", code: "provider-error" }); expect(await estimateTextMealWithOpenAi("arroz", { apiKey: "key", fetchImpl: async () => response(408, {}) })).toEqual({ status: "error", code: "provider-timeout" }); expect(await estimateTextMealWithOpenAi("arroz", { apiKey: "key", fetchImpl: async () => response(200, { status: "completed", output_text: "no-json" }) })).toEqual({ status: "error", code: "invalid-ai-response" }); expect(await estimateTextMealWithOpenAi("arroz", { apiKey: "key", fetchImpl: async () => response(200, { status: "completed", output: [{ type: "message", content: [{ type: "refusal" }] }] }) })).toEqual({ status: "error", code: "invalid-ai-response" }); });
});
