import { describe, expect, it } from "vitest";
import { buildVoiceInventoryBatchSaveItems, toVoiceInventoryBatchSaveInput } from "@/modules/inventory/voice-inventory-batch-save";
const item = { name: " Pollo ", quantity: 2, unit: "kg", location: "freezer", category: "protein", nutrition_basis: "per_100g", calories: 120, protein_g: 22, carbs_g: 0, fat_g: 3 };
describe("voice batch save schema", () => {
 it("accepts compatible strict inventory items", () => expect(toVoiceInventoryBatchSaveInput("123e4567-e89b-42d3-a456-426614174000", [item]).success).toBe(true));
 it("rejects empty, too-large, invalid and extra payloads", () => { expect(toVoiceInventoryBatchSaveInput("123e4567-e89b-42d3-a456-426614174000", []).success).toBe(false); expect(toVoiceInventoryBatchSaveInput("123e4567-e89b-42d3-a456-426614174000", Array.from({ length: 31 }, () => item)).success).toBe(false); for (const changed of [{ quantity: 0 }, { quantity: -1 }, { name: "" }, { name: "x".repeat(121) }, { unit: "box" }, { location: "garage" }, { category: "nope" }, { calories: -1 }, { nutrition_basis: "per_unit" }, { client_id: "x" }, { expires_at: "2026-01-01" }, { user_id: "x" }]) expect(toVoiceInventoryBatchSaveInput("123e4567-e89b-42d3-a456-426614174000", [{ ...item, ...changed }]).success).toBe(false); });
 it("rejects non-finite numbers", () => { for (const value of [NaN, Infinity, -Infinity]) expect(toVoiceInventoryBatchSaveInput("123e4567-e89b-42d3-a456-426614174000", [{ ...item, calories: value }]).success).toBe(false); });
 it("requires mapping real editable drafts before strict save validation", () => { const draft = { ...item, client_id: "draft", food_state: "raw" as const, confidence: "low" as const, issues: ["low-confidence"], review_acknowledged: true }; expect(toVoiceInventoryBatchSaveInput("123e4567-e89b-42d3-a456-426614174000", [draft]).success).toBe(false); const mapped = buildVoiceInventoryBatchSaveItems([draft as any]); expect(mapped.success).toBe(true); if (mapped.success) expect(Object.keys(mapped.data[0])).toEqual(["name", "quantity", "unit", "location", "category", "nutrition_basis", "calories", "protein_g", "carbs_g", "fat_g"]); });
});
