import { describe, expect, it } from "vitest";
import { type VoiceInventoryDraftItem, VoiceInventoryBatchOutputSchema, VOICE_INVENTORY_BATCH_MAX_ITEMS, VOICE_INVENTORY_BATCH_MAX_LENGTH, getVoiceInventoryDraftReadiness, getVoiceInventoryDraftStatus, normalizeEditedVoiceInventoryDraftItem, normalizeVoiceInventoryDraftItem, parseVoiceInventoryBatchInput } from "@/modules/inventory/voice-inventory-batch";
const item: Omit<VoiceInventoryDraftItem, "client_id"> = { name: "Pollo", quantity: 2, unit: "kg", location: "freezer", category: "protein", food_state: "raw", nutrition_basis: "per_100g", calories: 120, protein_g: 22, carbs_g: 0, fat_g: 3, package_count: null, package_size: null, package_size_unit: null, total_size: null, total_size_unit: null, confidence: "high", nutrition_assumptions: "Valores típicos por 100 g.", issues: [] };
describe("voice inventory batch", () => {
 it("enforces input and output limits", () => { expect(parseVoiceInventoryBatchInput(" ")).toBeNull(); expect(parseVoiceInventoryBatchInput("x".repeat(VOICE_INVENTORY_BATCH_MAX_LENGTH))).toBeTruthy(); expect(parseVoiceInventoryBatchInput("x".repeat(VOICE_INVENTORY_BATCH_MAX_LENGTH + 1))).toBeNull(); expect(VoiceInventoryBatchOutputSchema.safeParse({ items: Array.from({ length: VOICE_INVENTORY_BATCH_MAX_ITEMS }, () => item) }).success).toBe(true); expect(VoiceInventoryBatchOutputSchema.safeParse({ items: Array.from({ length: VOICE_INVENTORY_BATCH_MAX_ITEMS + 1 }, () => item) }).success).toBe(false); });
 it("derives mandatory issues and status from fields", () => { const incomplete = normalizeVoiceInventoryDraftItem({ ...item, quantity: null, location: null, calories: null, issues: [] }); expect(incomplete.issues).toEqual(expect.arrayContaining(["quantity-missing", "location-unconfirmed", "nutrition-incomplete"])); expect(getVoiceInventoryDraftStatus({ ...incomplete, client_id: "local" })).toBe("Incompleto"); });
 it("recalculates issues after editing", () => { const draft = { ...normalizeVoiceInventoryDraftItem({ ...item, quantity: null, issues: ["package-size-missing", "ambiguous-product"] }), client_id: "local" }; const resolved = normalizeEditedVoiceInventoryDraftItem(draft, "quantity", 2); expect(resolved.issues).not.toContain("quantity-missing"); const named = normalizeEditedVoiceInventoryDraftItem(resolved, "name", "Espinacas congeladas 500 g"); expect(named.issues).not.toContain("ambiguous-product"); });
 it("resolves and lets the user correct a compound package conversion", () => { const draft = { ...item, package_count: 3, quantity: 3, unit: "ud" as const, package_size: 143, package_size_unit: "g" as const, nutrition_basis: "per_100g" as const, calories: 200, protein_g: 20, carbs_g: 10, fat_g: 5, issues: [], client_id: "tuna" }; const resolved = { ...normalizeVoiceInventoryDraftItem(draft), client_id: "tuna" }; expect(resolved).toMatchObject({ quantity: 3, unit: "ud", nutrition_basis: "per_unit", calories: 286 }); const corrected = normalizeEditedVoiceInventoryDraftItem(resolved, "package_size", 150); expect(corrected).toMatchObject({ calories: 300, protein_g: 30 }); });
 it("keeps units without observed weight unresolved", () => { const draft = normalizeVoiceInventoryDraftItem({ ...item, name: "Tortillas", quantity: 6, unit: "ud", package_count: 6, package_size: null, package_size_unit: null, nutrition_basis: null, calories: null, protein_g: null, carbs_g: null, fat_g: null, issues: ["package-size-missing", "nutrition-incomplete"] }); expect(draft.package_size).toBeNull(); expect(draft.issues).toContain("package-size-missing"); });
 it("keeps a complete draft without a category ready to save", () => { const draft = { ...normalizeVoiceInventoryDraftItem({ ...item, category: null }), client_id: "local" }; expect(draft.issues).not.toContain("category-missing"); expect(getVoiceInventoryDraftReadiness(draft).saveReady).toBe(true); });
});
