import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
describe("voice inventory batch UI contracts", () => {
 it("uses shared persistent dictation and prevents stale previews", () => { const input = source("components/inventory/VoiceInventoryBatchInput.tsx"); const hook = source("components/voice/usePersistentSpeechRecognition.ts"); expect(input).toContain("usePersistentSpeechRecognition"); expect(input).toContain("mergeVoiceTranscript"); expect(input).toContain("requestVersion"); expect(input).toContain("setItems([])"); expect(input).toContain("maxLength={VOICE_INVENTORY_BATCH_MAX_LENGTH}"); expect(hook).toContain('recognition.lang = "es-ES"'); expect(hook).toContain("recognition.continuous = true"); });
 it("keeps preview editable and non-persistent", () => { const preview = source("components/inventory/VoiceInventoryBatchPreview.tsx"); expect(preview).toContain("normalizeEditedVoiceInventoryDraftItem"); expect(preview).toContain("Eliminar"); expect(preview).toContain("Tipo de envase"); expect(preview).toContain("Lata"); expect(preview).toContain("Paquete"); expect(preview).toContain("Se recordará: 1"); expect(preview).not.toMatch(/Guardar|insert\(|rpc\(|supabase/i); });
 it("maps drafts, preserves catalog metadata after review, and prevents concurrent saves", () => { const input = source("components/inventory/VoiceInventoryBatchInput.tsx"); expect(input).toContain("buildVoiceInventoryBatchSaveItems"); expect(input).toContain("buildVoiceInventoryBatchCatalogMetadata"); expect(input).toContain("saveVoiceInventoryBatchAction(submissionId, saveItems.data, catalogMetadata.data)"); expect(input).not.toContain("saveVoiceInventoryBatchAction(submissionId, items)"); expect(input).toContain("try {"); expect(input).toContain("catch"); expect(input).toContain("finally {"); expect(input).toContain("setSaving(false);"); expect(input).toContain("if (saving || !submissionId) return"); });
 it("refreshes the inventory only after a successful batch save", () => { const input = source("components/inventory/VoiceInventoryBatchInput.tsx"); const success = input.slice(input.indexOf('if (result.status === "error")'), input.indexOf("} catch")); expect(input).toContain("useRouter"); expect(success).toContain("router.refresh()"); });
});
